Improve ws error handling
IBM/fluent-forward-go pull request #31
Opened 2021-12-07 13:48 UTC by ericmillin

WS error handling should now be more intuitive and give the client more control. Also simplified client state management

2021-12-07 13:52 UTC, ericmillin commented on fluent/client/ws/connection.go
> +				wsc.setConnState(ConnStateError)
Setting ConnStateError prevents Close from trying to send close message to peer.

https://github.com/IBM/fluent-forward-go/pull/31/files#diff-f4b3bc6364cb918edaf959e398736dddfa88d9ee58ed9c9c094c00d11d429e6eR195

2021-12-07 16:40 UTC, BernhardSchmid requested changes
The idea of the changes looks reasonable to me. Running the test a little bit different ...

Running `ginkgo -r -untilItFails` will report an invalid memory address

```
[1638894705] Fluent Suite - 0/0 specs  SUCCESS! 134.402µs PASS
[1638894705] Client Suite - 23/28 specs ••••••••••••••panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x12bf8c4]

goroutine 55 [running]:
github.com/IBM/fluent-forward-go/fluent/client.(*WSClient).connect.func1()
	/Users/bus/fargo/fluent-forward-go/fluent/client/ws_client.go:176 +0x24
created by github.com/IBM/fluent-forward-go/fluent/client.(*WSClient).connect
	/Users/bus/fargo/fluent-forward-go/fluent/client/ws_client.go:170 +0x1e5

Tests failed on attempt #2
```

Running `ginkgo -r -race -untilItFails` reports a data race
```
[1638894672] Client Suite - 23/28 specs •••==================
WARNING: DATA RACE
Read at 0x00c0001b4170 by goroutine 34:
  github.com/IBM/fluent-forward-go/fluent/client.(*WSClient).connect.func1()
      /Users/bus/fargo/fluent-forward-go/fluent/client/ws_client.go:176 +0x3d

Previous write at 0x00c0001b4170 by goroutine 7:
  github.com/IBM/fluent-forward-go/fluent/client.(*WSClient).Disconnect()
      /Users/bus/fargo/fluent-forward-go/fluent/client/ws_client.go:193 +0x175
  github.com/IBM/fluent-forward-go/fluent/client_test.glob..func4.4()
      /Users/bus/fargo/fluent-forward-go/fluent/client/ws_client_test.go:87 +0x451
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync()
      /Users/bus/data/development/go/pkg/mod/github.com/onsi/ginkgo@v1.16.4/internal/leafnodes/runner.go:113 +0x10c
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).run()
      /Users/bus/data/development/go/pkg/mod/github.com/onsi/ginkgo@v1.16.4/internal/leafnodes/runner.go:64 +0x157
  github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run()
```

2021-12-08 09:44 UTC, BernhardSchmid approved these changes

2021-12-08 09:44 UTC, BernhardSchmid commented
LGTM - approved.

2021-12-08 09:47 UTC, merged